mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: isDeleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    default-enum-type-handler: org.cuit.echo.seon.commonweb.enumeration.BaseEnumHandler